"""empty message

Revision ID: 24a6b4c0c539
Revises: c19a0ccfc824
Create Date: 2019-07-18 17:40:31.777129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a6b4c0c539'
down_revision = 'c19a0ccfc824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TargetRole', sa.Column('target_role_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TargetRole', 'target_role_data')
    # ### end Alembic commands ###
