"""empty message

Revision ID: c19a0ccfc824
Revises: 
Create Date: 2019-07-17 16:29:54.504048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19a0ccfc824'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'users', ['name'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
