"""empty message

Revision ID: c590ca111b15
Revises: de762459d3aa
Create Date: 2019-08-24 09:15:09.263878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c590ca111b15'
down_revision = 'de762459d3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TargetSubActivity',
    sa.Column('target_subactivity_name', sa.String(length=200), nullable=False),
    sa.Column('target_subactivity_display_name', sa.String(length=250), nullable=True),
    sa.Column('target_subactivity_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('target_subactivity_name')
    )
    op.drop_table('TargetActivity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TargetActivity',
    sa.Column('target_activity_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('target_activty_desc', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('target_activity_data', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('target_activity_name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('TargetSubActivity')
    # ### end Alembic commands ###
