"""empty message

Revision ID: de762459d3aa
Revises: 24a6b4c0c539
Create Date: 2019-08-24 05:15:18.749285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de762459d3aa'
down_revision = '24a6b4c0c539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TargetActivity',
    sa.Column('target_activity_name', sa.String(length=200), nullable=False),
    sa.Column('target_activty_desc', sa.String(length=250), nullable=True),
    sa.Column('target_activity_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('target_activity_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TargetActivity')
    # ### end Alembic commands ###
